### ISSUE TITLE
Document how to obtain raindrop_token and raindrop_collection_id

### ISSUE THREAD

**Issue by jk** [thevops/youtube-tracker#2]
I wasn't able to find the `raindrop_token` and `raindrop_collection_id` which is needed for the `production.yml`. I've created a new application under https://app.raindrop.io/settings/integrations but I suppose that's not the correct way to obtain the token. And for the collection id I have no clue where to get it (I've created a raindrop account several years ago and never used it since).

**Comment by thevops** [comment]
@jk documentation added ✅
